"""Shared telemetry-only RCA dataset contract."""

from __future__ import annotations

VISIBLE_CSV_FILES = ("metrics.csv", "logs.csv", "traces.csv", "business.csv")
LEGACY_METRICS_CSV = "simple_metrics.csv"

BUSINESS_CSV_HEADER = ["timestamp", "window", "metric", "value", "unit", "source"]
BUSINESS_WINDOWS = {"baseline", "fault", "cooldown"}
BUSINESS_UNITS = {"count", "ratio", "ms", "score"}
BUSINESS_SOURCES = {
    "business_probe",
    "business_data_quality",
    "business_entity_distribution",
}

FORBIDDEN_VISIBLE_TOKENS = (
    "INV-",
    "target_invariant",
    "business_journey",
    "business_entity",
    "semantic_violation_type",
    "root_cause_service",
    "target_service",
    "target_db",
    "target_table",
    "target_field",
    "modify_value",
    "injector",
    "fault_family",
    "fault_dimension",
    "expected_propagation",
    "affected_services",
    "propagation_depth",
    "quality_decision",
    "prism_verdict",
    "PRISM",
    "gold",
    "candidate",
    "rejected",
    "label",
)

ALLOWED_BUSINESS_METRICS = {
    "login_success_rate",
    "login_business_invalid_rate",
    "login_timeout_rate",
    "login_http_5xx_rate",
    "login_http_4xx_rate",
    "login_request_exception_rate",
    "login_json_decode_error_rate",
    "login_latency_ms_p95",
    "login_latency_ms_p99",
    "trip_search_success_rate",
    "trip_search_business_invalid_rate",
    "trip_search_timeout_rate",
    "trip_search_http_5xx_rate",
    "trip_search_http_4xx_rate",
    "trip_search_request_exception_rate",
    "trip_search_json_decode_error_rate",
    "trip_search_latency_ms_p95",
    "trip_search_latency_ms_p99",
    "contacts_fetch_success_rate",
    "contacts_fetch_business_invalid_rate",
    "contacts_fetch_timeout_rate",
    "contacts_fetch_http_5xx_rate",
    "contacts_fetch_http_4xx_rate",
    "contacts_fetch_request_exception_rate",
    "contacts_fetch_json_decode_error_rate",
    "contacts_fetch_latency_ms_p95",
    "contacts_fetch_latency_ms_p99",
    "order_read_success_rate",
    "order_read_business_invalid_rate",
    "order_read_timeout_rate",
    "order_read_http_5xx_rate",
    "order_read_http_4xx_rate",
    "order_read_request_exception_rate",
    "order_read_json_decode_error_rate",
    "order_read_latency_ms_p95",
    "order_read_latency_ms_p99",
    "booking_precheck_success_rate",
    "booking_precheck_business_invalid_rate",
    "booking_precheck_timeout_rate",
    "booking_precheck_http_5xx_rate",
    "booking_precheck_http_4xx_rate",
    "booking_precheck_request_exception_rate",
    "booking_precheck_json_decode_error_rate",
    "booking_precheck_latency_ms_p95",
    "booking_precheck_latency_ms_p99",
    "payment_submit_success_rate",
    "payment_submit_business_invalid_rate",
    "payment_submit_timeout_rate",
    "payment_submit_http_5xx_rate",
    "payment_submit_http_4xx_rate",
    "payment_submit_request_exception_rate",
    "payment_submit_json_decode_error_rate",
    "payment_submit_latency_ms_p95",
    "payment_submit_latency_ms_p99",
    "cancel_submit_success_rate",
    "cancel_submit_business_invalid_rate",
    "cancel_submit_timeout_rate",
    "cancel_submit_http_5xx_rate",
    "cancel_submit_http_4xx_rate",
    "cancel_submit_request_exception_rate",
    "cancel_submit_json_decode_error_rate",
    "cancel_submit_latency_ms_p95",
    "cancel_submit_latency_ms_p99",
    "addon_query_success_rate",
    "addon_query_business_invalid_rate",
    "addon_query_timeout_rate",
    "addon_query_http_5xx_rate",
    "addon_query_http_4xx_rate",
    "addon_query_request_exception_rate",
    "addon_query_json_decode_error_rate",
    "addon_query_latency_ms_p95",
    "addon_query_latency_ms_p99",
    "payment_without_order_count",
    "order_without_payment_count",
    "amount_mismatch_count",
    "negative_amount_count",
    "invalid_order_status_count",
    "illegal_order_transition_count",
    "duplicate_seat_assignment_count",
    "inventory_overbook_count",
    "preserve_without_order_count",
    "cancel_without_inventory_release_count",
    "rebook_state_mismatch_count",
    "orphan_addon_reference_count",
    "addon_order_lookup_failure_count",
    "foreign_contact_booking_count",
    "trip_invalid_route_reference_count",
    "trip_invalid_station_reference_count",
    "config_missing_key_count",
    "config_out_of_range_count",
    "orphan_notification_order_count",
    "orphan_voucher_order_count",
    "orphan_delivery_order_count",
    "food_delivery_orphan_count",
    "consign_price_invalid_count",
    "train_type_invalid_count",
    "wallet_balance_invalid_count",
    "order_status_distribution_jsd",
    "payment_state_distribution_jsd",
    "seat_assignment_distribution_jsd",
    "trip_route_distribution_jsd",
    "config_value_distribution_jsd",
}

PRIMARY_BUSINESS_SUFFIXES = (
    "_success_rate",
    "_business_invalid_rate",
    "_timeout_rate",
    "_http_5xx_rate",
    "_http_4xx_rate",
    "_request_exception_rate",
    "_json_decode_error_rate",
    "_count",
    "_distribution_jsd",
)

LATENCY_BUSINESS_SUFFIXES = ("_latency_ms_p95", "_latency_ms_p99")
